### ISSUE TITLE
Add logic to commit models generated in the devel branch to the devel branch of icub-models

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-model-generator#124]
The PR https://github.com/robotology/icub-model-generator/pull/123 introduces a change that is only compatible with gazebo-yarp-plugins 3.3 (currently in the devel branch). For this reason, we need to introduce the `devel` branch also in this repo and in icub-models, and add a bit of generation on the Travis script that automatically pushes the models to icub-models, to push the generate models to the `devel` branch of icub-models when a new commit is pushed to the icub-model-generator's `devel` branch.

**Comment by traversaro** [comment]
Actually, now that I think of this more, it seems to be more aligned with our workflow that we keep a single branch on this repo (i.e. `master`) and then push any change from it to the `devel` branch of icub-models. We can then manually merge from `devel` to `master` of icub-models whenever we do a new release, so approximately every three months.

What do you think of this @Nicogene ?

**Comment by Nicogene** [comment]
Sounds good to me!

**Comment by traversaro** [comment]
This change was implemented in https://github.com/robotology/icub-model-generator/pull/141, and it already saved us to deploy a bad regression for iCub2 models in stable branches as described in https://github.com/robotology/icub-models/issues/50 .
