### ISSUE TITLE
Decide where to store the hand_mk3 model

### ISSUE THREAD

**Issue by fiorisi** [robotology/icub-model-generator#130]
The iCubTech team Dev would like to discuss where to store the files used to generate the new hand model and where to store the URDF model in [icub-models](https://github.com/robotology/icub-models).

Concerning the source files one possibility is to create a folder named `hand_mk3` in this directory:
https://github.com/robotology/icub-model-generator/tree/master/simmechanics/data

Concerning the URDF model if we store the file in the [iCub](https://github.com/robotology/icub-models/tree/master/iCub) folder we might have a mess inside of the `conf` and `meshes` subfolders.
One solution is to create another folder `A` in the [repository root](https://github.com/robotology/icub-models). Inside `A` we create a dedicated folder `hand_mk3` that contains the URDF model with the `conf` and `meshes` subfolders.

If this solution is viable, and we want to use the folder `A` also to store the URDF of other robot parts or gadgets maybe `A` can be named `components`.

Finally, do you think that the purpose of the repository `icub-models` is still preserved?

cc @traversaro @gabrielenava @DanielePucci @pattacini @ale-git @lornat75

**Comment by traversaro** [comment]
I like your proposal @fiorisi , and `components` seems to be a good name to me.

**Comment by fiorisi** [comment]
The PR has been opened. Closing this discussion for the time being.

**Comment by fiorisi** [comment]
cc @vvasco @Nicogene @vtikha
